# Generated by Django 3.2 on 2023-07-10 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0004_temp_scopes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstoken',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='authorizedclient',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='description',
        ),
        migrations.DeleteModel(
            name='Scope',
        )
    ]
