# Generated by Django 3.2 on 2023-07-10 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0006_recreate_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstoken',
            name='temp_scope',
        ),
        migrations.RemoveField(
            model_name='authorizedclient',
            name='temp_scope',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='temp_scope',
        ),
        migrations.DeleteModel(
            name='TempScope',
        ),
    ]
